import React from "react";
import GlassCard from "@/components/ui/GlassCard";

interface RecommendationModalProps {
  isLight: boolean;
  selected: any;
  onClose: () => void;
}

const RecommendationModal: React.FC<RecommendationModalProps> = ({ isLight, selected, onClose }) => (
  <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
    <GlassCard className={`w-11/12 max-w-2xl p-6 ${isLight ? 'bg-white/90 border border-slate-200' : ''}`}>
      <div className="flex items-start justify-between">
        <div>
          <h3 className={`text-lg font-semibold ${isLight ? 'text-slate-900' : 'text-white'}`}>{selected.village}</h3>
          <div className={`text-sm ${isLight ? 'text-emerald-700' : 'text-emerald-200'}`}>Recommended: {selected.scheme}</div>
        </div>
        <div>
          <button
            onClick={onClose}
            className={`text-sm px-3 py-1 rounded-md ${isLight ? 'bg-emerald-100 text-emerald-800 hover:bg-emerald-200' : 'bg-white/10 text-white hover:bg-white/20'}`}
          >
            Close
          </button>
        </div>
      </div>

      <GlassCard className={`mt-4 grid grid-cols-1 md:grid-cols-2 gap-4 ${isLight ? 'bg-white/90 border border-slate-200' : ''}`}>
        <div>
          <h4 className={`text-sm font-medium ${isLight ? 'text-emerald-700' : 'text-emerald-200'}`}>Priority score</h4>
          <div className={`text-2xl font-bold ${isLight ? 'text-slate-900' : 'text-white'}`}>
            {(selected.score * 100).toFixed(0)}%
          </div>
          <div className={`mt-3 text-sm ${isLight ? 'text-emerald-700' : 'text-emerald-200'}`}>
            This recommendation is generated by combining rule-based eligibility and
            AI-derived indicators.
          </div>
        </div>
        <div>
          <h4 className={`text-sm font-medium ${isLight ? 'text-emerald-700' : 'text-emerald-200'}`}>Actions</h4>
          <div className="mt-2 flex flex-col gap-2">
            <button className={`inline-flex items-center gap-2 px-4 py-2 rounded-md ${isLight ? 'bg-emerald-600 hover:bg-emerald-700 text-white' : 'bg-emerald-600 hover:bg-emerald-700 text-white'}`}>
              Create Plan
            </button>
            <button className={`inline-flex items-center gap-2 px-4 py-2 rounded-md ${isLight ? 'border border-emerald-300 text-emerald-800 hover:bg-emerald-50' : 'border border-white/10 text-white/90 hover:bg-white/10'}`}>
              Assign to Officer
            </button>
          </div>
        </div>
      </GlassCard>
    </GlassCard>
  </div>
);

export default RecommendationModal;